### ISSUE TITLE
Child process's stdout & stderr both mixed into stderr, by accident?

### ISSUE THREAD

**Issue by joonas-fi** [tiiuae/mission-data-recorder#6]
https://github.com/tiiuae/mission-data-recorder/blob/2e56780de3e60acf2187547827092993e3a13586/recorder.go#L101-L103

Probably a copy-paste oversight?

If on purpose, it could be a good idea to clarify in comment why this is done to build understanding and to remove doubts on whether this was an accident

**Comment by ezzkoram** [comment]
Well spotted :+1: @lassilaiho can comment - I believe this is by accident not by design?

**Comment by lassilaiho** [comment]
I apologize for the delay in the answer. I hadn't noticed this issue due to bad choices in my notification settings. Sending all output from `ros2 bag record` command to stderr is intentional. The idea was to separate the output of `ros2 bag record` command from the output of mission-data-recorder, but I don't know if this has actually been useful in practice. It can be changed if it would be clearer or more useful that way.

**Comment by lassilaiho** [comment]
Except that the log package sends messages to stderr by default, so output from `ros2 bag record` command should have been written to stdout and not stderr, which means that is actually a bug.
